# shellcheck shell=bash
# The shared local-model services.
#
# One Ollama holding the weights, one LiteLLM in front of it translating wire formats, both on a
# network of their own. Sourced by bin/docker-code; every name below is fixed so that a second
# session finds the services the first one started rather than starting its own.
#
# Why central: seven tools that each keep their own copy of a 20 GB model is 140 GB of the same
# bytes. ~/docker-code/models is the one place they live, and every agent reaches the same daemon.

MODELS_NETWORK="${DOCKER_CODE_MODELS_NETWORK:-docker-code-net}"
MODELS_LABEL="com.ruepp.docker-code"

OLLAMA_CONTAINER="${DOCKER_CODE_OLLAMA_CONTAINER:-docker-code-ollama}"
OLLAMA_IMAGE="${DOCKER_CODE_OLLAMA_IMAGE:-ollama/ollama:latest}"
OLLAMA_PORT=11434

LITELLM_CONTAINER="${DOCKER_CODE_LITELLM_CONTAINER:-docker-code-litellm}"
LITELLM_IMAGE="${DOCKER_CODE_LITELLM_IMAGE:-ghcr.io/berriai/litellm:main-stable}"
LITELLM_PORT=4000

# Not a secret: it authenticates a container to a gateway on a private Docker network that has no
# published port. It exists because LiteLLM refuses to serve without one.
LOCAL_API_KEY="docker-code-local"

# Same reasoning as the registry mirror's subnet: a fixed range is one you can name in a route or a
# corporate firewall exception, and it stays inside Docker's own default pool. Empty hands the
# choice back to Docker.
MODELS_SUBNET="${DOCKER_CODE_MODELS_SUBNET-172.30.31.0/24}"

models_dir()   { printf '%s\n' "${STORAGE_ROOT%/}/models"; }
ollama_store() { printf '%s\n' "$(models_dir)/ollama"; }
litellm_dir()  { printf '%s\n' "$(models_dir)/litellm"; }

# ---------------------------------------------------------------------------------------------
# The gateway's configuration
#
# A wildcard entry rather than one line per model: whatever is pulled into Ollama is servable
# immediately, so `docker-code models pull <anything>` needs no config edit and no restart. Written
# once and then left alone — a user who tunes it keeps their version.
# ---------------------------------------------------------------------------------------------
models_write_litellm_config() {
    local dir config
    dir="$(litellm_dir)"
    config="${dir}/config.yaml"

    mkdir -p "${dir}" || return 1
    [ -e "${config}" ] && return 0

    cat >"${config}" <<EOF
# Generated by docker-code on first start. Yours to edit — it is never overwritten.
#
# The wildcard maps any model name straight through to Ollama, so a model pulled with
#   docker-code models pull qwen3-coder:7b
# is usable as "qwen3-coder:7b" here without another line in this file.
model_list:
  - model_name: "*"
    litellm_params:
      model: "ollama_chat/*"
      api_base: "http://${OLLAMA_CONTAINER}:${OLLAMA_PORT}"

litellm_settings:
  drop_params: true

general_settings:
  master_key: "${LOCAL_API_KEY}"
EOF
}

# ---------------------------------------------------------------------------------------------
# Lifecycle
#
# Every failure degrades to a warning and a session without local models, exactly like the registry
# mirror: a model gateway is worth less than the session it would otherwise prevent.
# ---------------------------------------------------------------------------------------------
models_create_network() {
    local err
    models_network_create=(docker network create)
    [ -z "${MODELS_SUBNET}" ] || models_network_create+=(--subnet "${MODELS_SUBNET}")
    models_network_create+=(--label "${MODELS_LABEL}=models" "${MODELS_NETWORK}")

    err="$("${models_network_create[@]}" 2>&1 >/dev/null)" && return 0

    # Losing the race to a session that started at the same moment is not a failure.
    docker network inspect "${MODELS_NETWORK}" >/dev/null 2>&1 && return 0
    [ -z "${err}" ] || warn "${err}"
    return 1
}

models_ensure_network() {
    local current

    if ! docker network inspect "${MODELS_NETWORK}" >/dev/null 2>&1; then
        models_create_network
        return
    fi

    [ -n "${MODELS_SUBNET}" ] || return 0

    # Space-separated and matched with the separators: a network can carry more than one config, and
    # a substring match would find 172.30.31.0/2 inside 172.30.31.0/24.
    current=" $(docker network inspect \
        -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' "${MODELS_NETWORK}" 2>/dev/null || true) "
    case "${current}" in
        *" ${MODELS_SUBNET} "*) return 0 ;;
    esac

    if ! docker network rm "${MODELS_NETWORK}" >/dev/null 2>&1; then
        warn "the ${MODELS_NETWORK} network is in use, so it keeps the subnet it was created with"
        return 0
    fi
    models_create_network
}

models_container_running() {
    [ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null || true)" = "true" ]
}

models_start_ollama() {
    local store
    models_container_running "${OLLAMA_CONTAINER}" && return 0

    docker rm -f "${OLLAMA_CONTAINER}" >/dev/null 2>&1 || true

    store="$(ollama_store)"
    mkdir -p "${store}" || { warn "cannot create ${store}"; return 1; }

    # Not --rm: unlike the registry mirror, stopping this one should not throw away a container whose
    # restart is the difference between "models are here" and a fresh pull. The weights are on the
    # bind mount either way, but the container is cheap to keep and quick to restart.
    models_ollama_create=(docker run --detach
        --name "${OLLAMA_CONTAINER}"
        --network "${MODELS_NETWORK}"
        --label "${MODELS_LABEL}=models"
        --restart unless-stopped
        --volume "${store}:/root/.ollama")

    # A GPU if the host has one wired into Docker; CPU inference otherwise. Asking for a GPU that is
    # not there is a hard `docker run` error, so `auto` detects rather than assumes.
    #
    # Only the runtime *names* are matched, not the whole .Runtimes structure: that renders as ~6 KB
    # of capability and seccomp detail per runtime, and grepping it for a vendor name is a false
    # positive waiting to happen.
    #
    # The detection sees the NVIDIA Container Toolkit's registered runtime. A host wired up through
    # CDI only has no such runtime, so `auto` finds nothing there and falls back to the CPU — which
    # is why the value is more than a boolean: DOCKER_CODE_MODELS_GPU=1 forces `--gpus all`, and
    # anything else is passed to --gpus verbatim, e.g. "device=0" or "all,capabilities=compute".
    case "${DOCKER_CODE_MODELS_GPU:-auto}" in
        0|false|none|off)
            ;;
        auto)
            if docker info --format '{{range $name, $r := .Runtimes}}{{$name}} {{end}}' 2>/dev/null |
                grep -qw nvidia; then
                models_ollama_create+=(--gpus all)
            fi
            ;;
        1|true|all)
            models_ollama_create+=(--gpus all)
            ;;
        *)
            models_ollama_create+=(--gpus "${DOCKER_CODE_MODELS_GPU}")
            ;;
    esac

    # Published only when asked for. The agents reach it over the Docker network, so by default
    # nothing new listens on the host — and when it is published it is bound to loopback.
    if [ -n "${DOCKER_CODE_MODELS_PUBLISH:-}" ]; then
        models_ollama_create+=(--publish "127.0.0.1:${OLLAMA_PORT}:${OLLAMA_PORT}")
    fi

    models_ollama_create+=("${OLLAMA_IMAGE}")

    # Docker's own message, not a swallowed exit code. The failure people actually hit here is
    # asking for a GPU the host cannot provide —
    #   failed to discover GPU vendor from CDI: no known GPU vendor found
    # — and a silent "did not start" would send them looking in the wrong place entirely.
    local err
    err="$("${models_ollama_create[@]}" 2>&1 >/dev/null)" && return 0

    # Losing the race to a session that started it first is not a failure.
    models_container_running "${OLLAMA_CONTAINER}" && return 0

    [ -z "${err}" ] || warn "${err}"
    case "${err}" in
        *GPU*|*gpu*|*nvidia*)
            warn "that is the GPU request failing. DOCKER_CODE_MODELS_GPU=0 runs on the CPU;"
            warn "see the GPU section of LOCAL-MODELS.md for what the host needs."
            ;;
    esac
    return 1
}

models_start_litellm() {
    local dir
    models_container_running "${LITELLM_CONTAINER}" && return 0

    docker rm -f "${LITELLM_CONTAINER}" >/dev/null 2>&1 || true

    models_write_litellm_config || { warn "cannot write the LiteLLM config"; return 1; }
    dir="$(litellm_dir)"

    models_litellm_create=(docker run --detach
        --name "${LITELLM_CONTAINER}"
        --network "${MODELS_NETWORK}"
        --label "${MODELS_LABEL}=models"
        --restart unless-stopped
        --volume "${dir}:/app/config"
        --env "LITELLM_MASTER_KEY=${LOCAL_API_KEY}")

    if [ -n "${DOCKER_CODE_MODELS_PUBLISH:-}" ]; then
        models_litellm_create+=(--publish "127.0.0.1:${LITELLM_PORT}:${LITELLM_PORT}")
    fi

    models_litellm_create+=("${LITELLM_IMAGE}"
        --config /app/config/config.yaml --port "${LITELLM_PORT}")

    "${models_litellm_create[@]}" >/dev/null 2>&1 && return 0
    models_container_running "${LITELLM_CONTAINER}"
}

models_up() {
    models_ensure_network || return 1
    models_start_ollama || return 1

    # The gateway is what gives Gemini CLI a local model at all, but a session that only needs
    # Ollama's own API should not fail because LiteLLM did.
    models_start_litellm || warn "the LiteLLM gateway did not start; tools that need it (gemini) stay on their cloud provider"
    return 0
}

models_down() {
    local c
    for c in "${LITELLM_CONTAINER}" "${OLLAMA_CONTAINER}"; do
        # Stop first, remove second: SIGTERM and time to finish a write, rather than SIGKILL into it.
        docker stop "${c}" >/dev/null 2>&1 || true
        docker rm "${c}" >/dev/null 2>&1 || true
    done
    docker network rm "${MODELS_NETWORK}" >/dev/null 2>&1 || true
}

models_status() {
    local c state
    printf '%-24s %-10s %s\n' CONTAINER STATE IMAGE
    for c in "${OLLAMA_CONTAINER}" "${LITELLM_CONTAINER}"; do
        state="$(docker inspect -f '{{.State.Status}}' "${c}" 2>/dev/null || echo "-")"
        printf '%-24s %-10s %s\n' "${c}" "${state}" \
            "$(docker inspect -f '{{.Config.Image}}' "${c}" 2>/dev/null || echo "-")"
    done
    echo
    echo "weights:  $(ollama_store)"
    if [ -d "$(ollama_store)" ]; then
        echo "on disk:  $(du -sh "$(ollama_store)" 2>/dev/null | cut -f1)"
    fi
    echo "network:  ${MODELS_NETWORK}${MODELS_SUBNET:+ (${MODELS_SUBNET})}"
    models_gpu_status

    # The endpoints and the key, printed rather than only documented.
    #
    # A session started with DOCKER_CODE_LOCAL=1 gets all of this set for it, but anyone configuring
    # a tool by hand needs the key — and the first place they look is this command, not LOCAL-MODELS.md.
    # It is not a secret: it authenticates a container to a gateway on a private Docker network with
    # no published port, and it exists only because LiteLLM refuses to answer without one.
    echo
    echo "endpoints, for configuring a tool by hand (inside a DOCKER_CODE_LOCAL=1 session):"
    printf '  %-34s %s\n' "http://localhost:${OLLAMA_PORT}/v1"  "OpenAI-compatible   (codex, qwen, opencode)"
    printf '  %-34s %s\n' "http://localhost:${OLLAMA_PORT}"     "Anthropic-compatible (claude)"
    printf '  %-34s %s\n' "http://localhost:${LITELLM_PORT}"    "Gemini-compatible    (gemini)"
    echo "  API key: ${LOCAL_API_KEY}"
    if [ -z "${DOCKER_CODE_MODELS_PUBLISH:-}" ]; then
        echo "  (no host ports; DOCKER_CODE_MODELS_PUBLISH=1 publishes them on 127.0.0.1)"
    else
        printf '  from the host: http://127.0.0.1:%s and http://127.0.0.1:%s\n' \
            "${OLLAMA_PORT}" "${LITELLM_PORT}"
    fi
}

# Two different questions, both worth answering here: was the container *given* a GPU, and did Ollama
# *find* one. They come apart — a container started with --gpus whose driver is too old for the
# runtime still falls back to the CPU, and the difference is the whole diagnosis.
models_gpu_status() {
    local requests inference library name

    requests="$(docker inspect -f '{{json .HostConfig.DeviceRequests}}' "${OLLAMA_CONTAINER}" 2>/dev/null || true)"
    case "${requests}" in
        ''|null|'[]')
            echo "gpu:      not requested — the container was started for CPU inference"
            echo "          (DOCKER_CODE_MODELS_GPU=1 forces it; see LOCAL-MODELS.md)"
            ;;
        *)
            echo "gpu:      requested at start (--gpus)"
            ;;
    esac

    # Ollama says what it settled on once, at startup: library=cpu or library=cuda/rocm.
    inference="$(docker logs "${OLLAMA_CONTAINER}" 2>&1 | grep 'msg="inference compute"' | tail -n 1 || true)"
    if [ -n "${inference}" ]; then
        library="$(printf '%s' "${inference}" | sed -n 's/.*library=\([^ ]*\).*/\1/p')"
        name="$(printf '%s' "${inference}" | sed -n 's/.*description=\([^ ]*\).*/\1/p')"
        # On a CPU host both fields say "cpu"; only print the description when it adds something.
        [ "${name}" = "${library}" ] && name=""
        echo "ollama:   computing on ${library:-?}${name:+ (${name})}"
    fi
}

models_exec_ollama() {
    if ! models_container_running "${OLLAMA_CONTAINER}"; then
        die "the model services are not running; start them with: docker-code models up"
    fi
    docker exec -i "${OLLAMA_CONTAINER}" ollama "$@"
}

# What the session launcher needs to know: the port forwards to install inside the container, and
# the URL the tool should be pointed at. Both depend on which wire format the agent speaks.
models_bridge_spec() {
    printf '%s:%s:%s %s:%s:%s\n' \
        "${OLLAMA_PORT}" "${OLLAMA_CONTAINER}" "${OLLAMA_PORT}" \
        "${LITELLM_PORT}" "${LITELLM_CONTAINER}" "${LITELLM_PORT}"
}

models_url_for_mode() {
    case "$1" in
        ollama-anthropic|openai-compat) printf 'http://localhost:%s\n' "${OLLAMA_PORT}" ;;
        litellm-*)                      printf 'http://localhost:%s\n' "${LITELLM_PORT}" ;;
        *)                              return 1 ;;
    esac
}
